<div class="space-y-8" wire:poll.5s>
    <h1 class="text-3xl font-bold text-fg-alt mb-6">QR Code Batch Manager</h1>

    <div class="bg-bkg-alt border border-border rounded-lg shadow-sm">
        <div class="p-6 border-b border-border">
            <h2 class="text-xl font-semibold text-fg-alt">Create New QR Code Batch</h2>
            <p class="mt-1 text-sm text-fg-soft">Generate a new set of unique QR codes for a specific campaign.</p>
        </div>
        <div class="p-6">
            <form wire:submit="createBatch" class="space-y-6">
                <div>
                    <label for="selectedCampaignId" class="block text-sm font-medium text-fg-soft">Select
                        Campaign</label>
                    <select wire:model="selectedCampaignId" id="selectedCampaignId"
                        class="mt-1 block w-full form-select">
                        <option value="">-- Choose a campaign --</option>
                        @foreach ($campaigns as $campaign)
                            <option value="{{ $campaign['id'] }}">{{ $campaign['name'] }}</option>
                        @endforeach
                    </select>
                    @error('selectedCampaignId')
                        <span class="text-danger text-sm mt-1">{{ $message }}</span>
                    @enderror
                </div>
                <div>
                    <label for="batchName" class="block text-sm font-medium text-fg-soft">Batch Name</label>
                    <input wire:model="batchName" type="text" id="batchName"
                        placeholder="e.g., Diwali Promo - 500g Packets" class="mt-1 block w-full form-input">
                    @error('batchName')
                        <span class="text-danger text-sm mt-1">{{ $message }}</span>
                    @enderror
                </div>
                <div>
                    <label for="quantity" class="block text-sm font-medium text-fg-soft">Quantity</label>
                    <input wire:model="quantity" type="number" id="quantity" class="mt-1 block w-full form-input">
                    @error('quantity')
                        <span class="text-danger text-sm mt-1">{{ $message }}</span>
                    @enderror
                </div>
                <div>
                    <button type="submit"
                        class="bg-primary text-primary-fg font-bold py-2 px-4 rounded-lg hover:opacity-90 disabled:opacity-50"
                        wire:loading.attr="disabled">
                        <span wire:loading.remove wire:target="createBatch">Generate Batch</span>
                        <span wire:loading wire:target="createBatch">Generating...</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="bg-bkg-alt border border-border rounded-lg shadow-sm">
        <div class="p-6">
            <h2 class="text-xl font-semibold text-fg-alt">Generated Batches</h2>
        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full text-sm text-left text-fg-soft">
                <thead class="text-xs text-fg-soft uppercase bg-bkg-soft">
                    <tr>
                        <th class="px-6 py-3">Batch / Campaign</th>
                        <th class="px-6 py-3">Quantity</th>
                        <th class="px-6 py-3">Generated By</th>
                        <th class="px-6 py-3">Date (IST)</th>
                        <th class="px-6 py-3">PDF Status</th>
                        <th class="px-6 py-3">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-border">
                    @forelse ($batches as $batch)
                        <tr wire:key="batch-{{ $batch->id }}" class="hover:bg-bkg-soft">
                            <td class="px-6 py-4 font-medium text-fg-alt">
                                {{ $batch->name }}
                                <span class="block text-xs text-fg-soft">{{ $batch->campaign->name }}</span>
                            </td>
                            <td class="px-6 py-4">{{ number_format($batch->quantity) }}</td>
                            <td class="px-6 py-4">{{ $batch->generator->name }}</td>
                            <td class="px-6 py-4">
                                {{ $batch->created_at->timezone('Asia/Kolkata')->format('d M Y, h:i A') }}</td>
                            <td class="px-6 py-4">
                                <span
                                    class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full
                                    @switch($batch->pdf_status)
                                        @case('completed') bg-success/20 text-success @break
                                        @case('processing')
                                        @case('queued') bg-yellow-500/20 text-yellow-500 animate-pulse @break
                                        @case('failed') bg-red-500/20 text-danger @break
                                        @default bg-gray-500/20 text-fg-soft
                                    @endswitch
                                ">
                                    {{ ucfirst($batch->pdf_status) }}
                                </span>
                            </td>
                            <td class="px-6 py-4 text-sm font-medium">
                                <div class="flex items-center space-x-4 text-fg-soft">
                                    @if ($batch->pdf_status === 'completed')
                                        <a href="{{ route('admin.qr.download.pdf', $batch) }}"
                                            class="hover:text-primary" title="Download PDF"><svg
                                                xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                                fill="currentColor">
                                                <path fill-rule="evenodd"
                                                    d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
                                                    clip-rule="evenodd" />
                                            </svg></a>
                                    @else
                                        <a href="{{ route('admin.qr.export.pdf', $batch) }}" class="hover:text-primary"
                                            title="Generate PDF"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5"
                                                viewBox="0 0 20 20" fill="currentColor">
                                                <path fill-rule="evenodd"
                                                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z"
                                                    clip-rule="evenodd" />
                                            </svg></a>
                                    @endif
                                    <a href="{{ route('admin.qr.export.csv', $batch) }}" class="hover:text-primary"
                                        title="Export Master List (CSV)"><svg class="w-6 h-6" fill="none"
                                            stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4">
                                            </path>
                                        </svg>
                                    </a>
                                    <a href="{{ route('admin.qr.export.zip', $batch) }}" class="hover:text-primary"
                                        title="Export for Designers (ZIP)"><svg class="w-6 h-6" fill="none"
                                            stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z">
                                            </path>
                                        </svg></a>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="px-6 py-4 text-center text-fg-soft">No batches have been
                                generated yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="p-4">{{ $batches->links() }}</div>
    </div>
</div>
